version: '3.3'
services:
    hayati-bot:
        build: .
        ports:
            - '8080:8080'
        container_name: hayati-bot
        restart: always
        image: hayati-bot:latest
        volumes:
            - ${PWD}/logging.conf:/usr/src/app/logging.conf
