name: Build

on:
  push:
#    branches:
#      - main
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to ghcr
        id: login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/CSBatagi
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/CSBatagi/bot-Hayati
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: yes
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

