name: Deploy

on:
  push:
#    branches:
#      - main
#
jobs:
  deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/CSBatagi/bot-Hayati
          tags: |
            type=sha

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/123719540575/locations/global/workloadIdentityPools/ci-pool/providers/my-provider
          service_account: gha-hayati@esoteric-dryad-256520.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          
      - name: Test GCP Authentication
        run: gcloud compute instances list --project esoteric-dryad-256520

      - name: Use gcloud CLI
        run:  |
          gcloud compute instances update-container hayati-bedava \
          --container-image=ghcr.io/csbatagi/bot-hayati:${{steps.meta.outputs.tags}}  \
          --container-mount-host-path=mount-path=/usr/src/app/credentials.json,host-path=/var/secrets/credentials.json,mode=ro \
          --container-env BOT_TOKEN=${{secrets.DISCORD_TOKEN}} --zone=us-east1-b